Added kernel tags so we don't have to have complicated tag finding logic

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,19 +1,44 @@
 #!/bin/bash
 
 #
-# NOTE: We're assuming Ubuntu and HWE for now
+# To configure and build for a kernel other than the running kernel, set the
+# KERNEL_VERSION_FULL environment variable to the desired kernel version string.
 #
+# To build for a PVE release, set the LSB_CODENAME environment variable to "pve"
+# and the LSB_RELEASE variable to the desired Proxmox VE version (e.g., "pve-8.4").
+#
+
+# The output of "uname -r" for the desired kernel. If not set, this will use the running kernel version.
+# For Ubuntu kernels, we expect the corresponding linux-headers and linux-modules packages to be installed.
 _KERNEL_VERSION_FULL=${KERNEL_VERSION_FULL:="$(uname -r)"}
+
+# The output of "lsb_release -sr" for the desired distribution version.
+# For PVE builds, set this to the desired Proxmox VE version (e.g., "pve-8.4").
 _LSB_RELEASE=${LSB_RELEASE:="$(lsb_release -sr)"}
+
+# The output of "lsb_release -sc" for the desired distribution codename.
+# For PVE builds, set this to "pve".
 _LSB_CODENAME=${LSB_CODENAME:="$(lsb_release -sc)"}
+
+# This shouldn't be set directly since it's derived from the above, but allows for override just in case.
 _PATCH_DIR=${PATCH_DIR:="ubuntu/${_LSB_CODENAME}/hwe/${_KERNEL_VERSION_FULL}"}
-_KERNEL_TAG=${KERNEL_TAG:=""}
-PATCH_VERSION="1.0.0"
-EMAIL="${DEBEMAIL:=laplantes@ainfosec.com}"
-FULLNAME="${DEBFULLNAME:=Sean LaPlante}"
+
+# Allows specifying a particular kernel config file to use.
+# For PVE kernels, this will be ignored and overwritten to the config in the patch directory
+# For Ubuntu kernels, this will default to /boot/config-<kernel_version> or
+# /usr/src/linux-headers-<kernel_version>/.config if available.
 _USE_KERNEL_CONFIG=${USE_KERNEL_CONFIG:=""}
+
+# Allows overriding if needed, but defaults to the Module.symvers file from the linux-headers package.
+# For PVE kernels, this will be overwritten to the Module.symvers in the patch directory.
 _KERNEL_SYMVERS_FILE=${KERNEL_SYMVERS_FILE:="/usr/src/linux-headers-${_KERNEL_VERSION_FULL}/Module.symvers"}
 
+# These final variables are for the deb package versioning and maintainer info.
+_PATCH_VERSION=${PATCH_VERSION:="1.0.0"}
+_EMAIL="${DEBEMAIL:=laplantes@ainfosec.com}"
+_FULLNAME="${DEBFULLNAME:=Sean LaPlante}"
+
+# If this is a PVE kernel, override the patch directory, kernel config, and symvers file.
 if [[ ${_LSB_CODENAME} == "pve" ]]; then
     echo "Using PVE patch directory structure."
     _PATCH_DIR="pve/${_KERNEL_VERSION_FULL}"
@@ -21,6 +46,7 @@ if [[ ${_LSB_CODENAME} == "pve" ]]; then
     _KERNEL_SYMVERS_FILE=$(realpath "${_PATCH_DIR}/Module.symvers")
 fi
 
+# Make sure we actually have a patch directory to work with
 if [[ ! -d "${_PATCH_DIR}" ]]; then
     echo "No patch for ${_KERNEL_VERSION_FULL} in ${_LSB_CODENAME} HWE."
     echo "Make the ${_PATCH_DIR} directory and copy most recent patch files over to start working on the patch."
@@ -29,10 +55,23 @@ fi
 
 get_ubuntu_kernel_source() {
     local full_ver=""
+    local kernel_tag=""
+    local repo_url="git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/${_LSB_CODENAME}"
 
     echo "Getting Ubuntu kernel source. This could take a bit..."
 
-    # Figure out the name of the package
+    # If we saved the kernel tag to a file, use that and short-circuit
+    if [[ -f "ubuntu-kernel-tag" ]]; then
+        kernel_tag="$(cat ubuntu-kernel-tag)"
+        echo "ubuntu-kernel-tag file found in patch directory ${_PATCH_DIR}. Cloning specified tag: ${kernel_tag}."
+        if ! git clone --depth 1 --branch "${kernel_tag}" "${repo_url}" ./kernel; then
+            echo "Could not clone Ubuntu kernel source with tag ${kernel_tag}"
+            return 1
+        fi
+        return 0
+    fi
+
+    # Otherwise, try to get the right kernel source from apt.
     full_ver=$(apt-cache policy linux-image-unsigned-"${_KERNEL_VERSION_FULL}" | grep "Candidate:" | awk '{print $2}')
     if [[ -z "${full_ver}" || $? -ne 0 ]]; then
         echo "Could not find kernel package linux-image-unsigned-${_KERNEL_VERSION_FULL}"
@@ -45,40 +84,12 @@ get_ubuntu_kernel_source() {
         echo "Available versions listed are:"
         apt-cache showsrc linux | grep '^Version:'
 
-        REPO_URL="git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/${_LSB_CODENAME}"
-
-        # Gotta find it somewhere
-        FALLBACK_TAG=$(git ls-remote --tags git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/noble | grep "${full_ver%~*}" | cut -d/ -f3- | head -n1)
-
-        # Create a few tags to try
-        GIT_TAGS=(
-            "Ubuntu-hwe-${full_ver}"
-            "Ubuntu-hwe-${full_ver%~*}"
-            "Ubuntu-${full_ver}"
-            "Ubuntu-${full_ver%~*}"
-            "Ubuntu-${_KERNEL_VERSION_FULL}"
-            "Ubuntu-hwe-${_KERNEL_VERSION_FULL}"
-            "${FALLBACK_TAG}"
-        )
-        echo "Falling back to Git clone: ${REPO_URL}"
-        for GIT_TAG in "${GIT_TAGS[@]}"; do
-            echo "Trying to clone tag ${GIT_TAG}..."
-            if git clone --depth 1 --branch "${GIT_TAG}" "${REPO_URL}" ./kernel; then
-                echo "Successfully cloned kernel from Git at tag ${GIT_TAG}"
-                break
-            else
-                echo "Failed to find tag ${GIT_TAG} at ${REPO_URL}"
-            fi
-        done
-        if [[ ! -d "./kernel" ]]; then
-            echo "Failed to download kernel source from Git as well. Cannot continue."
-            return 2
-        fi
-    else
-        mv linux*"$(echo "${_KERNEL_VERSION_FULL}" | cut -d- -f 1)/" kernel
-        rm -f linux*.dsc linux*.tar.gz linux*.diff.gz
+        echo "Update the patch directory to include an ubuntu-kernel-tag file with the correct git tag to use."
+        return 1
     fi
 
+    mv linux*"$(echo "${_KERNEL_VERSION_FULL}" | cut -d- -f 1)/" kernel
+    rm -f linux*.dsc linux*.tar.gz linux*.diff.gz
     return 0
 }
 
@@ -95,7 +106,7 @@ get_pve_kernel_source() {
         echo "No ubuntu-kernel-tag file found in patch directory ${_PATCH_DIR}"
         return 1
     fi
-    if [[ ! -f config-*-pve ]]; then
+    if [[ ! -f "${_USE_KERNEL_CONFIG}" ]]; then
         echo "No config file found for PVE kernel in patch directory ${_PATCH_DIR}"
         return 1
     fi
@@ -194,9 +205,9 @@ truncate -s0 config.mk
     echo "WORKING_DIR=${_PATCH_DIR}"
     echo "KERNEL_CONFIG_FILE=${_USE_KERNEL_CONFIG}"
     echo "KERNEL_SYMVERS_FILE=${_KERNEL_SYMVERS_FILE}"
-    echo "PATCH_VERSION=${PATCH_VERSION}"
+    echo "PATCH_VERSION=${_PATCH_VERSION}"
     echo "INSTALL_DIR=/lib/modules/${_KERNEL_VERSION_FULL}/updates/introvirt/"
-    echo "DEB_NAME=kvm-introvirt-${_KERNEL_VERSION_FULL}.${_LSB_RELEASE}-${PATCH_VERSION}.deb"
+    echo "DEB_NAME=kvm-introvirt-${_KERNEL_VERSION_FULL}.${_LSB_RELEASE}-${_PATCH_VERSION}.deb"
     echo "KERNEL_VERSION_FULL=${_KERNEL_VERSION_FULL}"
 } >> config.mk
 
@@ -213,11 +224,11 @@ sed -i "s/KERNEL_VERSION_FULL=\"<<<REPLACED_BY_CONFIGURE>>>\"/KERNEL_VERSION_FUL
 # Build the changelog
 truncate -s0 debpkg/DEBIAN/changelog
 cat << EOF > debpkg/DEBIAN/changelog
-kvm-introvirt (${_KERNEL_VERSION_FULL}.${_LSB_RELEASE}-${PATCH_VERSION}~${_LSB_CODENAME}1) ${_LSB_CODENAME}; urgency=medium
+kvm-introvirt (${_KERNEL_VERSION_FULL}.${_LSB_RELEASE}-${_PATCH_VERSION}~${_LSB_CODENAME}1) ${_LSB_CODENAME}; urgency=medium
 
-  * kvm-introvirt patch ${PATCH_VERSION} for ${_KERNEL_VERSION_FULL}
+  * kvm-introvirt patch ${_PATCH_VERSION} for ${_KERNEL_VERSION_FULL}
 
- -- ${FULLNAME} <${EMAIL}>  $(date -u)
+ -- ${_FULLNAME} <${_EMAIL}>  $(date -u)
 EOF
 
 # Build the control
