Patch fixes, cleanup, 6.14.0-37 support, and helper scripts for patch dev
* Updated patch with MMU fixes and some debug logging. Added git diff patch just in case I messed up quilt
* Added script to build, sign, and hot-swap kvm.ko and kvm-intel.ko for testing with secure bot on. 
* Patched 6.8.0-90
* CI fixes for automated builds in Github actions
* Shellcheck added for quality
* Added badges to README
* Updated configure script to support configuring/building a kernel version other than the one running 
* Added fallback to clone git if source package is unavailable in apt
* Patch for 6.14.0-37-generic
* Added helper script for building a deb with self-signed introvirt kernel modules.
* Fixed postinst and postrm to handle AMD and Intel

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,27 +3,74 @@
 #
 # NOTE: We're assuming Ubuntu and HWE for now
 #
-KERNEL_VERSION_FULL="$(uname -r)"
-LSB_RELEASE=$(lsb_release -sr)
-LSB_CODENAME=$(lsb_release -sc)
-PATCH_DIR="ubuntu/$(lsb_release -sc)/hwe/$(uname -r)"
+_KERNEL_VERSION_FULL=${KERNEL_VERSION_FULL:="$(uname -r)"}
+_LSB_RELEASE=${LSB_RELEASE:="$(lsb_release -sr)"}
+_LSB_CODENAME=${LSB_CODENAME:="$(lsb_release -sc)"}
+PATCH_DIR="ubuntu/${_LSB_CODENAME}/hwe/${_KERNEL_VERSION_FULL}"
 PATCH_VERSION="1.0.0"
 EMAIL="${DEBEMAIL:=laplantes@ainfosec.com}"
 FULLNAME="${DEBFULLNAME:=Sean LaPlante}"
+_USE_KERNEL_CONFIG=${USE_KERNEL_CONFIG:=""}
 
-if [[ ! -d ${PATCH_DIR} ]]; then
-    echo "No patch for $(uname -r)".
+if [[ ! -d "${PATCH_DIR}" ]]; then
+    echo "No patch for ${_KERNEL_VERSION_FULL} in ${_LSB_CODENAME} HWE."
     echo "Make the ${PATCH_DIR} directory and copy most recent patch files over to start working on the patch."
     exit 1
 fi
 
-pushd ${PATCH_DIR} > /dev/null
+pushd "${PATCH_DIR}" > /dev/null || exit 1
 
 if [[ ! -d "./kernel" ]]; then
     echo "Getting kernel source. This could take a bit..."
-    apt source linux-image-unsigned-$(uname -r)
-    mv linux*$(uname -r | cut -d- -f 1)/ kernel
-    rm -f linux*.dsc linux*.tar.gz linux*.diff.gz
+
+    # Figure out the name of the package
+    FULL_VER=$(apt-cache policy linux-image-unsigned-"${_KERNEL_VERSION_FULL}" | grep "Candidate:" | awk '{print $2}')
+    if [[ -z "${FULL_VER}" || $? -ne 0 ]]; then
+        echo "Could not find kernel package linux-image-unsigned-${_KERNEL_VERSION_FULL}"
+        popd > /dev/null || exit 1
+        exit 1
+    fi
+
+    if ! apt-get source linux="${FULL_VER}"; then
+        echo "Could not download kernel source for linux-image-unsigned-${_KERNEL_VERSION_FULL} using apt."
+        echo "Possible this version isn't available in apt anymore."
+        echo "Available versions listed are:"
+        apt-cache showsrc linux | grep '^Version:'
+
+        REPO_URL="git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/${_LSB_CODENAME}"
+
+        # Gotta find it somewhere
+        FALLBACK_TAG=$(git ls-remote --tags git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/noble | grep "${FULL_VER%~*}" | cut -d/ -f3- | head -n1)
+
+        # Create a few tags to try
+        GIT_TAGS=(
+            "Ubuntu-hwe-${FULL_VER}"
+            "Ubuntu-hwe-${FULL_VER%~*}"
+            "Ubuntu-${FULL_VER}"
+            "Ubuntu-${FULL_VER%~*}"
+            "Ubuntu-${_KERNEL_VERSION_FULL}"
+            "Ubuntu-hwe-${_KERNEL_VERSION_FULL}"
+            "${FALLBACK_TAG}"
+        )
+        echo "Falling back to Git clone: ${REPO_URL}"
+        for GIT_TAG in "${GIT_TAGS[@]}"; do
+            echo "Trying to clone tag ${GIT_TAG}..."
+            if git clone --depth 1 --branch "${GIT_TAG}" "${REPO_URL}" ./kernel; then
+                echo "Successfully cloned kernel from Git at tag ${GIT_TAG}"
+                break
+            else
+                echo "Failed to find tag ${GIT_TAG} at ${REPO_URL}"
+            fi
+        done
+        if [[ ! -d "./kernel" ]]; then
+            echo "Failed to download kernel source from Git as well. Cannot continue."
+            popd > /dev/null || exit 1
+            exit 2
+        fi
+    else
+        mv linux*"$(echo "${_KERNEL_VERSION_FULL}" | cut -d- -f 1)/" kernel
+        rm -f linux*.dsc linux*.tar.gz linux*.diff.gz
+    fi
     chmod +x kernel/scripts/*.sh
 fi
 
@@ -34,21 +81,39 @@ if quilt unapplied; then
         echo "Then update the patch with \"quilt refresh\" followed by \"quilt pop -a\""
         echo "Make sure to \"quilt add <path>\" for any new files that may need to be patched before"
         echo "making any changes to those files."
-        popd > /dev/null
+        popd > /dev/null || exit 1
         exit 1
     fi
 fi
-popd > /dev/null
+popd > /dev/null || exit 1
+
+# Determine the kernel config we should use
+if [[ -z "${_USE_KERNEL_CONFIG}" || ! -f "${_USE_KERNEL_CONFIG}" ]]; then
+    if [[ -f "/boot/config-${_KERNEL_VERSION_FULL}" ]]; then
+        echo "Using running kernel config from /boot"
+        _USE_KERNEL_CONFIG="/boot/config-${_KERNEL_VERSION_FULL}"
+    elif [[ -f "/usr/src/linux-headers-${_KERNEL_VERSION_FULL}/.config" ]]; then
+        echo "Using kernel config from linux-headers"
+        _USE_KERNEL_CONFIG="/usr/src/linux-headers-${_KERNEL_VERSION_FULL}/.config"
+    else
+        echo "Using kernel config from patch directory"
+        _USE_KERNEL_CONFIG="${PATCH_DIR}/kernel/.config"
+    fi
+else
+    echo "Using user specified kernel config: ${_USE_KERNEL_CONFIG}"
+fi
 
 # Create the config.mk file
 truncate -s0 config.mk
-echo "WORKING_DIR=${PATCH_DIR}" >> config.mk
-echo "KERNEL_CONFIG_FILE=/boot/config-$(uname -r)" >> config.mk
-echo "KERNEL_SYMVERS_FILE=/usr/src/linux-headers-$(uname -r)/Module.symvers" >> config.mk
-echo "PATCH_VERSION=${PATCH_VERSION}" >> config.mk
-echo "INSTALL_DIR=/lib/modules/$(uname -r)/updates/introvirt/" >> config.mk
-echo "DEB_NAME=kvm-introvirt-${KERNEL_VERSION_FULL}.${LSB_RELEASE}-${PATCH_VERSION}.deb" >> config.mk
-echo "KERNEL_VERSION_FULL=${KERNEL_VERSION_FULL}" >> config.mk
+{
+    echo "WORKING_DIR=${PATCH_DIR}"
+    echo "KERNEL_CONFIG_FILE=${_USE_KERNEL_CONFIG}"
+    echo "KERNEL_SYMVERS_FILE=/usr/src/linux-headers-${_KERNEL_VERSION_FULL}/Module.symvers"
+    echo "PATCH_VERSION=${PATCH_VERSION}"
+    echo "INSTALL_DIR=/lib/modules/${_KERNEL_VERSION_FULL}/updates/introvirt/"
+    echo "DEB_NAME=kvm-introvirt-${KERNEL_VERSION_FULL}.${_LSB_RELEASE}-${PATCH_VERSION}.deb"
+    echo "KERNEL_VERSION_FULL=${KERNEL_VERSION_FULL}"
+} >> config.mk
 
 rm -f debpkg/DEBIAN/postinst debpkg/DEBIAN/postrm debpkg/DEBIAN/preinst
 cp -f debpkg/DEBIAN/postinst.tpl debpkg/DEBIAN/postinst
@@ -63,7 +128,7 @@ sed -i "s/KERNEL_VERSION_FULL=\"<<<REPLACED_BY_CONFIGURE>>>\"/KERNEL_VERSION_FUL
 # Build the changelog
 truncate -s0 debpkg/DEBIAN/changelog
 cat << EOF > debpkg/DEBIAN/changelog
-kvm-introvirt (${KERNEL_VERSION_FULL}.${LSB_RELEASE}-${PATCH_VERSION}~${LSB_CODENAME}1) ${LSB_CODENAME}; urgency=medium
+kvm-introvirt (${KERNEL_VERSION_FULL}.${_LSB_RELEASE}-${PATCH_VERSION}~${_LSB_CODENAME}1) ${_LSB_CODENAME}; urgency=medium
 
   * kvm-introvirt patch ${PATCH_VERSION} for ${KERNEL_VERSION_FULL}
 
