WIP: Patch improvements (#22)
* Patch improvements
* Some fixes for watchpoints
* Patch tweak for GFN in kvm_tdp_page_fault
* Better logging for 6.X patch
* Apply patch for 6.17.0-14
* Patches for 6.17.0-19-generic
* Patch for 6.17.0-20
* Updated github action files with new kernels
* Fix patch application issues
* Readme updates
* Fail KVM_SET_MEM_ACCESS_ENABLED when no TDP or non-Intel
* build-and-sign doesn't need to run as root
* Stubs to fix null deref on AMD. WIP: syscall monitoring on AMD
* Updated the postrm template to handle upgrade correctly
* Added kernel tag/branch name for CI/CD and update log output in configure to be more helpful

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -57,6 +57,12 @@ if [[ ! -d "${_PATCH_DIR}" ]]; then
     exit 1
 fi
 
+cleanup_kernel_source_folder() {
+    mv linux*"$(echo "${_KERNEL_VERSION_FULL}" | cut -d- -f 1 | cut -d. -f1,2)"*/ kernel || { echo "Failed to match kernel directory name"; return 1; }
+    rm -f linux*.dsc linux*.tar.gz linux*.diff.gz
+    return 0
+}
+
 get_ubuntu_kernel_source() {
     local full_ver=""
     local kernel_tag=""
@@ -70,12 +76,24 @@ get_ubuntu_kernel_source() {
         echo "ubuntu-kernel-tag file found in patch directory ${_PATCH_DIR}. Cloning specified tag: ${kernel_tag}."
         if ! git clone --depth 1 --branch "${kernel_tag}" "${repo_url}" ./kernel; then
             echo "Could not clone Ubuntu kernel source with tag ${kernel_tag}"
+	    echo "Try \"git ls-remote ${repo_url}\" and search for the appropriate branch for ${kernel_tag}."
             return 1
         fi
         return 0
     fi
 
+    # In this case, the `apt-get source linux-image-unsigned-...` should get the correct version
+    if [[ "${_KERNEL_VERSION_FULL}" == "$(uname -r)" ]]; then
+        if ! apt-get source linux-image-unsigned-"${_KERNEL_VERSION_FULL}"; then
+            echo "Unable to find linux-image-unsigned-${_KERNEL_VERSION_FULL} for running kernel. Fallback to apt-cache lookup."
+        else
+            cleanup_kernel_source_folder || return 1
+            return 0
+        fi
+    fi
+
     # Otherwise, try to get the right kernel source from apt.
+    echo "Kernel version full: ${_KERNEL_VERSION_FULL}"
     full_ver=$(apt-cache policy linux-image-unsigned-"${_KERNEL_VERSION_FULL}" | grep "Candidate:" | awk '{print $2}')
     if [[ -z "${full_ver}" || $? -ne 0 ]]; then
         echo "Could not find kernel package linux-image-unsigned-${_KERNEL_VERSION_FULL}"
@@ -92,8 +110,7 @@ get_ubuntu_kernel_source() {
         return 1
     fi
 
-    mv linux*"$(echo "${_KERNEL_VERSION_FULL}" | cut -d- -f 1)/" kernel
-    rm -f linux*.dsc linux*.tar.gz linux*.diff.gz
+    cleanup_kernel_source_folder || return 1
     return 0
 }
 
