Fallback to git if we can't get the source anywhere else

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -32,15 +32,26 @@ if [[ ! -d "./kernel" ]]; then
     fi
 
     if ! apt-get source linux="${FULL_VER}"; then
-        echo "Could not download kernel source for linux-image-unsigned-${_KERNEL_VERSION_FULL}"
-        echo "Possible this version isn't available anymore."
-        echo "Available versions:"
+        echo "Could not download kernel source for linux-image-unsigned-${_KERNEL_VERSION_FULL} using apt."
+        echo "Possible this version isn't available in apt anymore."
+        echo "Available versions listed are:"
         apt-cache showsrc linux | grep '^Version:'
-        popd > /dev/null || exit 1
-        exit 2  # We handle ret code 2 differently so CI doesn't fail
+
+        REPO_URL="git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/${_LSB_CODENAME}"
+        GIT_TAG="Ubuntu-${FULL_VER}"
+
+        echo "Falling back to Git clone: ${REPO_URL} at tag ${GIT_TAG}"
+        if git clone --depth 1 --branch "${GIT_TAG}" "${REPO_URL}" ./kernel; then
+            echo "Successfully cloned kernel from Git at tag ${GIT_TAG}"
+        else
+            echo "Failed to find tag ${GIT_TAG} at ${REPO_URL}"
+            popd > /dev/null || exit 1
+            exit 2
+        fi
+    else
+        mv linux*"$(echo "${_KERNEL_VERSION_FULL}" | cut -d- -f 1)/" kernel
+        rm -f linux*.dsc linux*.tar.gz linux*.diff.gz
     fi
-    mv linux*"$(echo "${_KERNEL_VERSION_FULL}" | cut -d- -f 1)/" kernel
-    rm -f linux*.dsc linux*.tar.gz linux*.diff.gz
     chmod +x kernel/scripts/*.sh
 fi
 
