CI stuff

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -71,8 +71,11 @@ jobs:
           LSB_CODENAME=${{ matrix.config.codename}} \
           LSB_RELEASE=${{ matrix.config.release}} \
           USE_KERNEL_CONFIG=/usr/src/linux-headers-${{ matrix.config.kernel }}/.config \
-          ./configure
-
+          ./configure || { test $? -eq 2 && ret=2 && exit 0 || exit 1; }
+          if [[ $ret -eq 2 ]]; then
+              echo "Cannot automate this kernel build. The kernel source is not available in apt for this version!"
+              exit 0
+          fi
           make -j$(nproc) package
         shell: bash
       - name: Archive debian packages
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -37,7 +37,7 @@ if [[ ! -d "./kernel" ]]; then
         echo "Available versions:"
         apt-cache showsrc linux | grep '^Version:'
         popd > /dev/null || exit 1
-        exit 0  # So CI doesn't fail
+        exit 2  # We handle ret code 2 differently so CI doesn't fail
     fi
     mv linux*"$(echo "${_KERNEL_VERSION_FULL}" | cut -d- -f 1)/" kernel
     rm -f linux*.dsc linux*.tar.gz linux*.diff.gz
